environment:
  NuGetApiKey:
    secure: JCSjKbmeUc+H++B2Ir3UaBL/XgnL9qAyPO++t5xrfCW9ku62GhkGx4XUx59Q7PqT
    
# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5


skip_commits:
  message: /updated readme.*|update readme.*s/

build: false

#before_test:
#  - ps: . .\Build.ps1

test_script:
  - ps: . .\Build.ps1

notifications:
  - provider: Slack
    auth_token:
      secure: G3SrU451ukZ4Lk+Olg0mhRcGLjfBR5l63MRUf4+pJhAs4o3iXy/BnMyiOvwWfVIiBSQNbfa943IogNY91Whj8w==